version: "3.8"
services:
  app:
    image: twitnic/cloudpower:latest
    working_dir: /var/www/cloudpower
    volumes:
      - ../frontend:/var/www/cloudpower
      - $SSH_AUTH_SOCK:/tmp/agent.sock
    environment:
      - DB_HOST=database
      - SSH_AUTH_SOCK=/tmp/agent.sock
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    depends_on:
      - database
  database:
    image: mariadb:10.4
    volumes:
      - ./db:/var/lib/mysql
    command: mysqld --sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      - "MYSQL_ROOT_PASSWORD=foobar"
      - "TZ=Europe/Berlin"
      - "MYSQL_DATABASE=frontend"
      - "MYSQL_USER=foobar"
      - "MYSQL_PASSWORD=foobar"
    ports:
      - "33061:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
    depends_on:
      - database