version: "3.7"
services:
  app:
    image: twitnic/cloudpower:latest
    working_dir: /var/www/cloudpower
    volumes:
      - ./frontend:/var/www/cloudpower
      - ./ssh-keys:/root/.ssh
    environment:
      - DB_HOST=database
    ports:
      - "80:80"
      - "9000:9000"
    depends_on:
      - database
  database:
    image: mariadb:10.4
    volumes:
      - ./db:/var/lib/mysql
    command: mysqld --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      - "MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD"
      - "TZ=Europe/Berlin"
      - "MYSQL_DATABASE=frontend"
      - "MYSQL_USER=foobar"
      - "MYSQL_PASSWORD=foobar"
    ports:
      - "33061:3306"