version: "3.7"
services:
  app:
    image: twitnic/cloudpower:latest
    working_dir: /var/www/cloudpower
    volumes:
      - ./../frontend:/var/www/cloudpower
    environment:
      - DB_HOST=database
    ports:
      - "8080:80"
      - "9000:9000"
    depends_on:
      - database
  database:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=frontend"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=foobar"
      - "MYSQL_ROOT_PASSWORD=foobar"
    ports:
      - "33061:3306"